#!/usr/bin/env ruby

def valid(line)
  arr = line.split
  (0...arr.length).each do |i|
    perms = arr[i].chars.permutation
    (i+1...arr.length).each do |j|
      return false if perms.include?(arr[j].chars)
    end
  end
  return true
end

input = $stdin.readlines.map(&:chomp)

puts input.select { |line|
  valid(line)
}.length
