#!/usr/bin/env ruby

input = gets.chomp.split(',')

line = %w( a b c d e f g h i j k l m n o p )

#namdgkbhifpceloj

(1_000_000_000).times do
  line =
    line[13] +
    line[0] +
    line[12] +
    line[3] +
    line[6] +
    line[10] +
    line[1] +
    line[7] +
    line[8] +
    line[5] +
    line[15] +
    line[2] +
    line[4] +
    line[11] +
    line[14] +
    line[9]
end
